export const pages = [
    {
        value: '10', label: '10'
    },
    {
        value: '15', label: '15'
    },
    {
        value: '20', label: '20'
    },
    {
        value: '30', label: '30'
    },
    {
        value: '40', label: '40'
    },
    {
        value: '50', label: '50'
    },
]

export const titles = [
    "Engenheiro(a) de software",
    "Desenvolvedor(a) fullstack",
    "Assistente de obras",
    "Médico(a)",
    "Professor(a)",
    "Enfermeiro(a)",
    "Advogado(a)",
    "Contador(a)",
    "Engenheiro(a) civil",
    "Arquiteto(a)",
    "Gerente de projetos",
    "Analista de sistemas",
    "Designer gráfico",
    "Jornalista",
    "Consultor(a) financeiro",
    "Analista de marketing",
    "Farmacêutico(a)",
    "Policial",
    "Bombeiro(a)",
    "Empreendedor(a)",
    "Psicólogo(a)",
    "Ator/atriz",
    "Assistente social",
    "Gerente de vendas",
    "Analista de recursos humanos",
    "Analista de dados",
    "Operador(a) de máquinas",
    "Eletricista",
    "Motorista de entregas",
    "Cabeleireiro(a)",
    "Esteticista",
    "Cozinheiro(a)",
    "Garçom/garçonete",
    "Recepcionista",
    "Secretário(a)",
    "Fotógrafo(a)",
    "Fisioterapeuta",
    "Personal trainer",
    "Engenheiro(a) de produção",
    "Escritor(a)",
    "Cientista de dados",
    "Gerente de contas",
    "Agente de viagens",
    "Nutricionista",
    "Engenheiro(a) mecânico",
    "Assistente administrativo",
    "Veterinário(a)",
    "Piloto de avião",
    "Astrônomo(a)",
    "Motorista de ônibus",
    "Técnico(a) de informática",
    "Tradutor(a)",
    "Técnico(a) em enfermagem",
    "Padeiro(a)",
    "Pedreiro(a)",
    "Pintor(a)",
    "Cientista",
    "Gerente de RH",
    "Engenheiro(a) de segurança do trabalho",
    "Agente imobiliário",
    "Camareiro(a)",
    "Gerente de restaurante",
    "Analista financeiro",
    "Barista",
    "Repórter",
    "Produtor(a) de TV",
    "Caminhoneiro(a)",
    "Massoterapeuta",
    "Consultor(a) de vendas",
    "Técnico(a) em radiologia",
    "Técnico(a) em eletrônica",
    "Analista de suporte técnico",
    "Pediatra",
    "Médico(a) veterinário(a)",
    "Fonoaudiólogo(a)",
    "Professor(a) de educação física",
    "Diplomata",
    "Engenheiro(a) de telecomunicações",
    "Agente de seguros",
    "Arquivista",
    "Terapeuta ocupacional",
    "Designer de interiores",
    "Motorista de táxi",
    "Manicure/pedicure",
    "Maquiador(a)",
    "Investigador(a) particular",
    "Marceneiro(a)",
    "Mecânico(a) de automóveis",
    "Cabeleireiro(a) canino",
    "Técnico(a) em segurança do trabalho",
    "Web designer",
    "Editor(a)",
    "Engenheiro(a) de qualidade",
    "Cientista ambiental",
    "Desenvolvedor(a) mobile",
    "Gerente de operações",
    "Biólogo(a)",
    "Designer de moda",
    "Analista de suporte técnico",
    "Técnico(a) de laboratório",
    "Escritor(a) técnico(a)",
    "Engenheiro(a) elétrico",
    "Gerente de contas",
    "Chef de cozinha",
    "Assessor(a) de imprensa",
    "Técnico(a) em manutenção",
    "Promotor(a) de vendas",
    "Engenheiro(a) químico",
    "Agente de atendimento ao cliente",
    "Artista plástico(a)",
    "Instrutor(a) de academia",
    "Editor(a) de vídeo",
    "Bancário(a)",
    "Confeiteiro(a)",
    "Biógrafo(a)",
    "Comissário(a) de bordo",
    "Técnico(a) em segurança do trabalho",
    "Operador(a) de telemarketing",
    "Pesquisador(a) científico(a)",
    "Designer de joias",
    "Editor(a) de fotos",
    "Agente cultural",
    "Técnico(a) em mecatrônica",
    "Gerente de logística",
    "Analista de qualidade",
    "Investidor(a)",
    "Animador(a) 3D",
    "Gerente de compras",
    "Assistente virtual",
    "Escultor(a)",
    "Fotógrafo(a) de casamentos",
    "Comprador(a)",
    "Gerente de operações",
    "Desenvolvedor(a) de jogos",
    "Designer de produto",
    "Técnico(a) em redes",
    "Revisor(a) de textos",
    "Técnico(a) agrícola",
    "Técnico(a) em eletricidade",
    "Gerente de TI",
    "Locutor(a)",
    "Redator(a) publicitário(a)",
    "Bombeiro(a) civil",
    "Gerente de marketing",
    "Supervisor(a) de vendas",
    "Técnico(a) em nutrição",
    "Analista de segurança da informação",
    "Estilista",
    "Designer de UX/UI",
    "Promotor(a) de eventos",
    "Ilustrador(a)",
    "Agente penitenciário(a)",
    "Técnico(a) em edificações",
    "Gerente administrativo",
    "Pesquisador(a) de mercado",
    "Gerente de atendimento ao cliente",
    "Técnico(a) em química",
    "Gerente de recursos humanos",
    "Encanador(a)",
    "Técnico(a) em radiologia",
    "Escritor(a) de conteúdo",
    "Carpinteiro(a)",
    "Engenheiro(a) de automação",
    "Gerente de produção",
    "Coordenador(a) de eventos",
    "Designer de som",
    "Técnico(a) em estética",
    "Investigador(a) de fraudes",
    "Dentista",
    "Analista de suporte ao cliente",
    "Gerente financeiro",
    "Consultor(a) de negócios",
    "Musicoterapeuta"
];